#!/bin/bash

mkdir bin
cd bin 
mkdir release
mkdir debug

if [ "$1" = "release" ]
then
    cd release
    cmake -DCMAKE_BUILD_TYPE=Release ../..
    make
    echo "Built target in bin/release/"
else
    cd debug 
    cmake -DCMAKE_BUILD_TYPE=Debug ../..
    make
fi